name: Swimm Verify
author: Swimm
description: Verify your Swimm units are up-to-date
runs:
  using: composite
  steps:
    - name: git configure
      shell: bash
      run: git config user.name temp && git config user.email temp@swimm.io
    - name: download Swimm
      shell: bash
      run: wget -q -O swimm_cli https://releases.swimm.io/ci/latest/packed-swimm-linux-cli
    - name: set execution permissions
      shell: bash
      run: chmod +x ./swimm_cli
    - name: swimm version
      shell: bash
      run: ./swimm_cli --version
    - name: verify
      shell: bash
      run: ./swimm_cli verify

branding:
  icon: 'check-square'  
  color: 'blue'
