name: Swimm Verify
author: Swimm
description: Verify your Swimm units are up-to-date
runs:
  using: composite
  steps:
    - name: git configure
      shell: bash
      run: git config user.name temp && git config user.email temp@swimm.io
    - name: download Swimm
      shell: bash
      run: curl -s https://api.github.com/repos/swimmio/SwimmReleases/releases/latest | grep 'browser_download_url.*swimm-cli' | cut -d '"' -f 4 | wget -O swimm_cli -qi -
    - name: swimm version
      shell: bash
      run: node swimm_cli --version
    - name: verify
      shell: bash
      run: node swimm_cli verify

branding:
  icon: 'check-square'  
  color: 'blue'
